apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anubis-api-ingress
  namespace: default
  annotations:
 #  kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
  #  app.kubernetes.io/managed-by: helm
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anubis-api-service
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: anubis-api-service
                port:
                  number: 80
          - path: /hook/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: notification-controller.flux-system
                port:
                  number: 80
