apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.yaml

  - helmrepo.yaml
  - helmrelease.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingressclass.yaml
  
 # - ./monitoring
  - ../flux-crds
#  - serviceaccount.yaml
