apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
#  - ./webhooks
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingressclass.yaml
  
# - flux-system-secret.enc.yaml
#  - ../flux-crds
#  - serviceaccount.yaml
patches:
  - path: serviceaccount-ecr.yaml
    target:
      kind: ServiceAccount
      name: image-reflector-controller
      namespace: flux-system
  
  