apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-reflector-controller
  namespace: flux-system
  annotations:
    # This forces the Flux pod to assume your new Terraform role
    ://amazonaws.com: arn:aws:iam::533267265715:role/anubis_role
