apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../flux-crds
# patches:
#   - target:
#       kind: Deployment
#       name: anubis-api
#     patch: |-
#       - op: replace
#         path: /spec/template/spec/containers/0/image
#         value: 533267265715.dkr.ecr.us-east-1.amazonaws.com/anubis-api:31c058128781a97b895f3cc9857046dc80a85a9d

