apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: anubis-cluster-addons
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com
  ref:
    branch: main
