apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: anubis-api
  namespace: flux-system
spec:
  interval: 1m
  image: 533267265715.dkr.ecr.us-east-1.amazonaws.com/anubis-api
  provider: aws   

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: anubis-api-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: anubis-api
  policy:
    alphabetical:
      order: asc  # Always pick the latest version

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: anubis-api-update
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: anubis-app-delivery-source
  git:
    checkout:
      ref:
        branch: main # ◄── Your secondary repo default branch (e.g., main or master)
    commit:
      author:
        email: dnjasper@hotmail.com
        name: dnjasper
      messageTemplate: gitops: automated image tag update to {{ .SelectedTarget.ImageTag }}
  update:
    strategy: Setters
    path: ../base
   